from pydantic import BaseModel

# response model for returning Action Sentences generated by the model
class ActionItems(BaseModel):
    data: list[str]

# request model for receiving scraped data from the extension client
class ScrapedData(BaseModel):
    name: str | None = "Empty!"
    data: str
